version: '3'
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pw
  app:
    image: ymt03/tenpo:latest
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis