spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: user
    password: pw
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources.add-mappings: false
  jpa:
    hibernate:
      ddl-auto: create-drop

server.error.whitelabel.enabled: false

api:
  rest:
  rate-limit:
    max-rpm: 10